server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    password: 84268426
    url: jdbc:mysql://localhost:3306/task_management_tool
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
